"""Regenerate the packed cloud bake worker the app sends to Runpod.

    python scripts/pack_cloud_worker.py           # rewrite the Dart constant
    python scripts/pack_cloud_worker.py --check   # exit 1 if it is stale

The worker can't ship as an asset: App Store Connect rejects any bundled .py as
unsigned code (ITMS-90035), so the app carries it gzipped and base64'd in Dart.
"""

from __future__ import annotations

import base64
import gzip
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "server" / "cloud" / "kazumi_bake_worker.py"
TARGET = ROOT / "lib" / "services" / "upscale" / "cloud" / "cloud_worker_packed.dart"

# Runpod accepted an 8 KB env value when this was measured (2026-10-06).
MAX_PACKED = 8000


def source() -> bytes:
    # core.autocrlf may hand us CRLF on Windows; the pod should get what git stores.
    return SOURCE.read_bytes().replace(b"\r\n", b"\n")


def packed() -> str:
    # mtime=0 keeps the output identical for identical source.
    data = gzip.compress(source(), compresslevel=9, mtime=0)
    return base64.b64encode(data).decode("ascii")


def render(value: str) -> str:
    return (
        "// Generated by scripts/pack_cloud_worker.py from "
        "server/cloud/kazumi_bake_worker.py. Do not edit.\n"
        f"const packedCloudWorker =\n    '{value}';\n"
    )


def unpack(dart: str) -> bytes | None:
    start = dart.find("'")
    end = dart.rfind("'")
    if start < 0 or end <= start:
        return None
    try:
        return gzip.decompress(base64.b64decode(dart[start + 1:end]))
    except Exception:
        return None


def is_current() -> bool:
    return TARGET.exists() and unpack(TARGET.read_text(encoding="utf-8")) == source()


def main() -> int:
    if "--check" in sys.argv:
        if is_current():
            return 0
        print("cloud_worker_packed.dart is stale: run python scripts/pack_cloud_worker.py")
        return 1
    value = packed()
    if len(value) > MAX_PACKED:
        print(f"packed worker is {len(value)} chars, over the {MAX_PACKED} Runpod env limit")
        return 1
    TARGET.write_text(render(value), encoding="utf-8", newline="\n")
    print(f"wrote {TARGET.relative_to(ROOT).as_posix()} ({len(value)} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
